apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: fraud-detection
  labels:
    app.kubernetes.io/name: fraud-detection
    app.kubernetes.io/component: config
data:
  # ===== API CONFIGURATION =====
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  WORKERS: "2"
  
  # ===== PERFORMANCE SETTINGS =====
  MAX_BATCH_SIZE: "100"
  PREDICTION_CACHE_TTL: "300"
  REQUEST_TIMEOUT: "30"
  
  # ===== METRICS & MONITORING =====
  ENABLE_METRICS: "true"
  METRICS_PORT: "9090"
  HEALTH_CHECK_INTERVAL: "5"
  
  # ===== MLFLOW INTEGRATION =====
  MODEL_NAME: "fraud_detection_yandex_model"
  MODEL_ALIAS: "champion"
  MODEL_CACHE_DIR: "/app/cache/models"
  MODEL_REFRESH_INTERVAL: "3600"
  
  # ===== CORS SETTINGS =====
  CORS_ORIGINS: "*"
  CORS_METHODS: "GET,POST,OPTIONS"
  CORS_HEADERS: "*"

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: fraud-detection
  labels:
    app.kubernetes.io/name: fraud-detection
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # ===== MLFLOW CREDENTIALS =====
  MLFLOW_TRACKING_URI: "http://mlflow-server.airflow.svc.cluster.local:5000"
  MLFLOW_TRACKING_USERNAME: ""
  MLFLOW_TRACKING_PASSWORD: ""
  
  # ===== API SECURITY =====
  API_KEY: "your-secure-api-key-here"
  JWT_SECRET: "your-jwt-secret-here"
  ENCRYPT_KEY: "your-encryption-key-here"
  
  # ===== DATABASE CONNECTION (если используется) =====
  DATABASE_URL: "postgresql://user:password@postgres:5432/fraud_detection"