apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-api
  namespace: fraud-detection
  labels:
    app.kubernetes.io/name: fraud-detection
    app.kubernetes.io/component: api
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: fraud-detection
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fraud-detection
        app.kubernetes.io/component: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: fraud-detection-api
        image: nginx:alpine
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-api-demo-content
  namespace: fraud-detection
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>🛡️ Fraud Detection API - Demo</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
            .container { max-width: 800px; margin: auto; background: white; padding: 30px; border-radius: 10px; }
            .status { padding: 15px; background: #d4edda; border: 1px solid #c3e6cb; border-radius: 5px; margin: 20px 0; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🛡️ Fraud Detection API - Demo</h1>
            <div class="status">
                ✅ <strong>Status:</strong> Running in Kubernetes<br>
                🎯 <strong>Purpose:</strong> Демонстрация автоскейлинга HW_10<br>
                📊 <strong>Replicas:</strong> 4-6 (управляется HPA)
            </div>
            <h3>🎯 Цели HW_10</h3>
            <ul>
                <li>✅ Автоскейлинг от 4 до 6 экземпляров</li>
                <li>✅ Мониторинг с Prometheus и Grafana</li>
                <li>✅ Алертинг при >80% CPU</li>
                <li>✅ Airflow для переобучения модели</li>
            </ul>
        </div>
    </body>
    </html>
