apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: airflow
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mlflow
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mlflow
        app.kubernetes.io/component: server
    spec:
      containers:
      - name: mlflow-server
        image: python:3.11-slim
        command:
        - bash
        - -c
        - |
          pip install mlflow==2.8.1
          mlflow server \
            --host 0.0.0.0 \
            --port 5000 \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root ./artifacts
        ports:
        - name: http
          containerPort: 5000
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
  namespace: airflow
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/component: server
